### ISSUE TITLE
When I use the --namespaces parameter, the app is created successfully, but no traffic is generated

### ISSUE THREAD

**Issue by mark8s** [warm-metal/ms-demo-gen#1]
It may be because traffic-generator and gateway are not in the same namespace, gateway and other application services are not in the same namespace, and it is still not possible to cross namespaces. 

default deployment env :

```
containers:
      - env:
        - name: ENV_UPSTREAM
          value: gateway
```

maybe correct env ：

```
containers:
      - env:
        - name: ENV_UPSTREAM
          value: gateway.current_namespace
```
